name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: polymost=${{ matrix.use_polymost }} gl=${{ matrix.use_opengl }} nogtk=${{ matrix.without_gtk || 0 }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use_polymost: [ 0, 1 ]
        use_opengl: [ 0, 1 ]
        exclude:
          - use_polymost: 1
            use_opengl: 0
        include:
          - use_polymost: 1
            use_opengl: 'USE_GLES2'
            without_gtk: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libgtk-3-dev libfluidsynth-dev
      - name: Make
        run: |
          cd "$GITHUB_WORKSPACE"
          make USE_POLYMOST=${{ matrix.use_polymost }} \
               USE_OPENGL=${{ matrix.use_opengl }} \
               WITHOUT_GTK=${{ matrix.without_gtk || 0 }} \
               USE_ASM=0 \
               all
